// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Copyright 2023, DASH-Industry Forum. All rights reserved.

// Use of this source code is governed by a BSD-style

// license that can be found in the LICENSE.md file.

package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// sgaiSessionStatusPage renders the live SGAI session-status page. The polling
// logic lives in /static/sgai_session_status.js; host is exposed via data-api.
func sgaiSessionStatusPage(host string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>livesim2 — SGAI session status</title><style>\r\n\t\t  body { font-family: system-ui, sans-serif; margin: 0; background: #1b1b1f; color: #eee; }\r\n\t\t  header { padding: 8px 18px; background: #111; }\r\n\t\t  h1 { margin: 0; font-size: 18px; }\r\n\t\t  .titlebar { display: flex; align-items: center; justify-content: space-between; gap: 12px; }\r\n\t\t  .ctrls { display: flex; align-items: center; white-space: nowrap; }\r\n\t\t  .sub { color: #aaa; font-size: 13px; margin-top: 4px; }\r\n\t\t  .wrap { padding: 10px 18px; }\r\n\t\t  .meta { margin: 6px 0 14px; font-size: 14px; }\r\n\t\t  .meta b { color: #9cf; }\r\n\t\t  .pill { display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: 12px;\r\n\t\t          background: #2980b9; color: #fff; margin-left: 6px; }\r\n\t\t  table { border-collapse: collapse; width: 100%; font-size: 13px; }\r\n\t\t  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #333; vertical-align: top; }\r\n\t\t  th { color: #aaa; font-weight: 600; }\r\n\t\t  tr.decision td.kind { color: #fc9900; font-weight: 700; }\r\n\t\t  tr.beacon td.kind { color: #27ae60; font-weight: 700; }\r\n\t\t  code { color: #9cf; }\r\n\t\t  input { background: #111; color: #eee; border: 1px solid #444; border-radius: 4px;\r\n\t\t          padding: 4px 8px; font-size: 13px; }\r\n\t\t  button { background: #c0392b; color: #fff; border: none; border-radius: 4px;\r\n\t\t           padding: 4px 10px; font-size: 13px; cursor: pointer; margin-left: 6px; }\r\n\t\t  button:hover:enabled { background: #e74c3c; }\r\n\t\t  button:disabled { background: #555; cursor: default; }\r\n\t\t  a { color: #9cf; }\r\n\t\t  .empty { color: #888; font-style: italic; margin-top: 10px; }\r\n\t\t</style></head><body data-api=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(host)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/sgai_session_status.templ`, Line: 43, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><header><div class=\"titlebar\"><h1>SGAI session status</h1><span class=\"ctrls\"><button id=\"reset\" type=\"button\" title=\"Clear this session's recorded status\">Reset session</button> <span id=\"dot\"></span></span></div><div class=\"sub\">Session: <input id=\"sid\" placeholder=\"(none — listing all)\"> &nbsp;— live ad decisions &amp; impression beacons, polled every second</div></header><div class=\"wrap\"><div id=\"meta\" class=\"meta\"></div><div id=\"body\"></div></div><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(host + "/static/sgai_session_status.js")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/sgai_session_status.templ`, Line: 61, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
