// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Copyright 2026, DASH-Industry Forum. All rights reserved.

// Use of this source code is governed by a BSD-style

// license that can be found in the LICENSE.md file.

package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// steeringSessionStatusPage renders the live DASH Content Steering session-status page. The polling
// logic lives in /static/steering_session_status.js; host is exposed via data-api.
func steeringSessionStatusPage(host string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>livesim2 — Content Steering session status</title><link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(host + "/static/session_status.css")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/steering_session_status.templ`, Line: 15, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><style>\n\t\t  td { vertical-align: middle; }\n\t\t  button.switch { background: #2980b9; }\n\t\t  button:hover:enabled { filter: brightness(1.15); }\n\t\t  .pill.mode { background: #8e44ad; }\n\t\t  .bar { display: inline-block; height: 14px; background: #2980b9; border-radius: 3px;\n\t\t         vertical-align: middle; min-width: 1px; }\n\t\t  .bar.top { background: #27ae60; }\n\t\t  .rank { color: #888; }\n\t\t  .rank.top { color: #27ae60; font-weight: 700; }\n\t\t  h2.polls { font-size: 14px; color: #aaa; font-weight: 600; margin: 22px 0 6px; }\n\t\t  .verify.ok { color: #27ae60; font-weight: 700; }\n\t\t  .verify.bad { color: #e74c3c; font-weight: 700; }\n\t\t  .verify.none { color: #666; }\n\t\t  .ok { color: #27ae60; }\n\t\t  .bad { color: #e74c3c; }\n\t\t  tr.badrow td { background: #3a1f1f; }\n\t\t</style></head><body data-api=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(host)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/steering_session_status.templ`, Line: 35, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><header><div class=\"titlebar\"><h1>Content Steering session status</h1><span class=\"ctrls\"><button id=\"switch\" class=\"switch\" type=\"button\" title=\"Advance this session to the next CDN\">Switch CDN</button> <button id=\"reset\" type=\"button\" title=\"Clear this session's recorded status\">Reset session</button> <span id=\"dot\"></span></span></div><div class=\"sub\">Group (csid): <input id=\"csid\" placeholder=\"(none)\"> &nbsp; Session: <input id=\"sid\" placeholder=\"(none — listing all)\"> &nbsp;— live per-CDN segment requests &amp; current pathway priority, polled every second</div></header><div class=\"wrap\"><div id=\"meta\" class=\"meta\"></div><div id=\"body\"></div></div><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(host + "/static/session_status_common.js")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/steering_session_status.templ`, Line: 55, Col: 58}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></script><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(host + "/static/steering_session_status.js")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/livesim2/app/steering_session_status.templ`, Line: 56, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
